### ISSUE TITLE
Font too big

### ISSUE THREAD

**Issue by Cestb0n** [zhuowei/WDBFontOverride#70]
When I import custom fonts.reminds me.

**Comment by Shadowspear123** [comment]
Same issue, is there a workaround?

**Comment by Shadowspear123** [comment]
Hey @Cestb0n , did you find a solution for the issue?

**Comment by Cestb0n** [comment]
> Hey @Cestb0n , did you find a solution for the issue?

No, this should be a system limitation. So I found another font
